# Generated by Django 4.2.13 on 2024-06-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='updated_at',
        ),
    ]
