# Generated by Django 4.2.13 on 2024-06-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_category_slug_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(default='oz', max_length=10),
        ),
    ]
